"""
The syntactic module contains functions allowing to calculate notions related to grammatical complexity.
Use a tree based on spacy or NLTK i don't know yet.
Then obtain features such as average tree height, average number of noun/verb-phrases per sentence,
Longest/Average distance between sets, length of synctactic units (sentence/clause/paragraph) or a 
T-unit level, which is 1 main + subordinate(s) clause : amount of coordinated/sub clauses, nb of clauses per t-unit, etc...
"""

# Syntactic features ~ grammatical complexity :
# Parse tree features (avgtree height, or avg number of noun/verb-phrases per sentence)
# Grammatical relation features (between constituents in sentence, like longest/avg dist in relation sets generated by a parser)
# Complexity of syntactic unit features : length of syntactic unit at sentence, clause (any structure with subject and finit verb),
# or T-unit level (one main clause + any subordinate clause)
# Coordination/Subordination features : amount of coord/sub, and more features like nb of clause per T-unit or numb of coord phrases per clause etc
# 